### ISSUE TITLE
Created AppScan configuration file for Zowe Application Framework / Desktop Repositories

### ISSUE THREAD

**Issue by raymondyanli** [zowe/zss-auth#18]
I have created AppScan configuration files for the projects under "Zowe Application Framework / Desktop Repositories" and pull requests have been created as well.

Here are the project lists with AppScan configuration files:
sample-angular-app
sample-iframe-app
sample-react-app
tn3270-ng2
vt-ng2
zlux-app-manager
zlux-app-server
zlux-build
zlux-editor
zlux-file-explorer
zlux-grid
zlux-platform
zlux-server-framework
zlux-shared
zlux-widgets
zlux-workflow
zosmf-auth
zss-auth

The pull request number likes: https://github.com/zowe/zss-auth/pull/17
...
 
Please check them out, let me know if you have any concerns.

**Comment by kathysychan** [comment]
@1000TurquoisePogs Please review the PRs submitted by @raymondyanli and commit them to the Zowe repos so that we can automate the generation of AppScan static scanning reports and pass back to the Zowe Open Source community.

**Comment by 1000TurquoisePogs** [comment]
Seems finished now.
